// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ClassWizardCppFix
{
    internal sealed partial class Vsix
    {
        public const string Id = "ClassWizardCppFix.ab0e0ac1-9d37-42e0-97ef-fd674bf4455d";
        public const string Name = "ClassWizardCppFix";
        public const string Description = @"Moves the Class created by the Class Wizard to the selected Location for Cpp Projects.";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "Gamingtoday093";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
